version: '3.4'
services:
  work-trial-api:
    build:
      context: ..
      dockerfile: ./Dockerfile.dev
    ports:
      - 3002:3002
    depends_on:
      - postgres
    volumes:
      - ../src:/app/src
      - ../nodemon.json:/app/nodemon.json
    command: yarn dev
    platform: linux/x86_64
